name: 10xBikeTrails Build

on:
  push:
    branches:
      - master

env:
  NEXT_PUBLIC_SUPABASE_URL: '' #TODO: Fill with github secrets
  NEXT_PUBLIC_SUPABASE_ANON_KEY: '' #TODO: Fill with github secrets
  NEXT_PUBLIC_OPENROUTER_KEY: '' #TODO: Fill with github secrets
  NEXT_PUBLIC_OPENROUTER_API_URL: '' #TODO: Fill with github secrets
  NEXT_PUBLIC_OPENROUTER_MODEL: '' #TODO: Fill with github secrets
  NEXT_PUBLIC_OPENROUTER_APP_URL: '' #TODO: Fill with github secrets

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: npm ci
      - run: npm run test
      - run: npm run lint
      - run: npm run build
